name: CI Testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
      - name: npm install, build, and test
        run: | 
              npm ci --workspaces=false
              npm run lint || true
              npm run -w express-backend build
              npm run -w express-backend test || true
        working-directory: packages/express-backend
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/express-backend
